[package]
name = "blazelint"
version = "0.3.0"
edition = "2021"
authors = ["Chamal Randika Mallawaarachchi, Rukshan Ranasinghe, Subhoda Pathum"]
description = "A code linter for Ballerina programming language"
license = "MIT"
repository = "https://github.com/RuztyCrabs/Blazelint"
homepage = "https://github.com/RuztyCrabs/Blazelint"
documentation = "https://github.com/RuztyCrabs/Blazelint#readme"

[lib]
name = "blazelint"
path = "src/lib.rs"

[[bin]]
name = "blazelint"
path = "src/main.rs"

[dependencies]
once_cell = "1.19.0"
toml = "0.8.14"
serde = { version = "1.0.203", features = ["derive"] }
thiserror = "1.0.61"
clap = { version = "4.4", features = ["derive"] }

[dev-dependencies]
assert_cmd = "2.0"
tempfile = "3.10"
predicates = "3.0"

[[test]]
name = "cli_diagnostics_test"
path = "tests/cli_diagnostics_test.rs"

[[test]]
name = "config_test"
path = "tests/config_test.rs"

[[test]]
name = "cli_flags_test"
path = "tests/cli_flags_test.rs"
