#!/usr/bin/env bash
# Generate a large valid Ballerina file for performance testing
# Target: ~680k tokens (roughly equivalent to 10k-15k lines of code)

set -euo pipefail

OUTPUT_FILE="${1:-performance_test.bal}"
TARGET_FUNCTIONS=7000  # Generate ~7000 functions to reach ~680k tokens

echo "Generating large Ballerina file: $OUTPUT_FILE"
echo "Target: $TARGET_FUNCTIONS functions (~680k tokens)"

cat > "$OUTPUT_FILE" << 'EOF'
// Generated large Ballerina file for performance testing
// Auto-generated by Blazelint performance test generator

import ballerina/io;
import ballerina/math;
import ballerina/time;
import ballerina/log;

// Constants section
const MAX_SIZE = 1000;
const MIN_SIZE = 10;
const DEFAULT_MESSAGE = "performance test";
const PI_VALUE = 3.14159265359;
const E_VALUE = 2.71828182846;
const GOLDEN_RATIO = 1.61803398875;
const SQRT_2 = 1.41421356237;

EOF

# Generate many functions with different patterns
for i in $(seq 1 $TARGET_FUNCTIONS); do
    echo "Generating function $i/$TARGET_FUNCTIONS..." >&2
    
    # Function type rotation
    case $((i % 8)) in
        0)
            # Simple arithmetic function
            cat >> "$OUTPUT_FILE" << EOF
public function arithmeticFunction${i}(int a, int b, float c) returns int {
    int result = a + b * 2 - 5;
    float temp = c * PI_VALUE / 2.0;
    int finalResult = result + <int>temp;
    
    if finalResult > MAX_SIZE {
        finalResult = MAX_SIZE;
    } else if finalResult < MIN_SIZE {
        finalResult = MIN_SIZE;
    }
    
    return finalResult;
}

EOF
            ;;
        1)
            # String manipulation function  
            cat >> "$OUTPUT_FILE" << EOF
function stringProcessing${i}(string input, boolean uppercase) returns string {
    string processed = input;
    int length = input.length();
    
    if length > 0 {
        for int j in 0..<length {
            if j % 2 == 0 {
                processed = processed + "_even";
            } else {
                processed = processed + "_odd";
            }
        }
    }
    
    if uppercase {
        processed = processed.toUpperAscii();
    }
    
    return processed;
}

EOF
            ;;
        2)
            # Array/collection processing
            cat >> "$OUTPUT_FILE" << EOF
function arrayProcessing${i}() returns int[] {
    int[] numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
    int[] processed = [];
    
    foreach int num in numbers {
        int squared = num * num;
        int cubed = squared * num;
        
        if cubed % 2 == 0 {
            processed.push(cubed);
        } else {
            processed.push(squared);
        }
    }
    
    return processed;
}

EOF
            ;;
        3)
            # Conditional logic heavy function
            cat >> "$OUTPUT_FILE" << EOF
function conditionalLogic${i}(int x, int y, boolean flag) returns string {
    string result = "default";
    
    if x > y && flag {
        if x % 2 == 0 {
            result = "even_greater";
        } else {
            result = "odd_greater";
        }
    } else if x < y && !flag {
        result = x > 0 ? "positive_lesser" : "negative_lesser";
    } else if x == y {
        result = flag ? "equal_true" : "equal_false";
    } else {
        result = "fallback_case";
    }
    
    return result;
}

EOF
            ;;
        4)
            # Loop-heavy function
            cat >> "$OUTPUT_FILE" << EOF
function loopProcessing${i}(int iterations) returns int {
    int accumulator = 0;
    
    while iterations > 0 {
        for int k in 0..<10 {
            if k % 3 == 0 {
                accumulator += k * 2;
            } else if k % 3 == 1 {
                accumulator -= k;
            } else {
                accumulator *= 2;
                accumulator = accumulator % 1000;
            }
        }
        iterations -= 1;
    }
    
    return accumulator;
}

EOF
            ;;
        5)
            # Error handling and type checking
            cat >> "$OUTPUT_FILE" << EOF
function typeHandling${i}(int|string|float value) returns string {
    string result = "";
    
    if value is int {
        result = "Integer: " + value.toString();
    } else if value is string {
        result = "String: " + value;
    } else if value is float {
        result = "Float: " + value.toString();
    }
    
    int len = result.length();
    if len > 50 {
        result = result.substring(0, 50) + "...";
    }
    
    return result;
}

EOF
            ;;
        6)
            # Complex expressions and operator usage
            cat >> "$OUTPUT_FILE" << EOF
function complexExpressions${i}(int base) returns int {
    int result = base;
    
    // Bitwise operations
    result = result << 2;
    result = result ^ 0xFF;
    result = result | 0x0F;
    result = result & 0xF0;
    result = result >> 1;
    
    // Arithmetic combinations
    result += base * 3 - base / 2 + base % 7;
    result *= (base > 10) ? 2 : 3;
    
    // Boolean logic with arithmetic
    boolean isEven = result % 2 == 0;
    boolean isPositive = result > 0;
    
    if isEven && isPositive {
        result += 100;
    } else if !isEven && isPositive {
        result -= 50;
    } else {
        result = -result;
    }
    
    return result;
}

EOF
            ;;
        7)
            # Function with local variables and nested scopes
            cat >> "$OUTPUT_FILE" << EOF
function nestedScopes${i}(int param1, string param2) returns boolean {
    int localVar = param1;
    string localString = param2;
    boolean success = false;
    
    {
        int innerVar = localVar * 2;
        string innerString = localString + "_inner";
        
        if innerVar > 0 {
            final int constant = 42;
            int temp = innerVar + constant;
            
            if temp % 7 == 0 {
                success = true;
                localVar = temp;
            }
        }
    }
    
    if success {
        localString = localString.toUpperAscii();
        return localString.length() > 5;
    }
    
    return false;
}

EOF
            ;;
    esac
done

# Add a main function that calls some of the generated functions
cat >> "$OUTPUT_FILE" << EOF

// Main function to tie everything together
public function main() {
    io:println("Starting performance test...");
    
    // Call some generated functions
    int result1 = arithmeticFunction1(10, 20, 3.14);
    string result2 = stringProcessing2("test", true);
    int[] result3 = arrayProcessing3();
    
    io:println("Arithmetic result: " + result1.toString());
    io:println("String result: " + result2);
    io:println("Array length: " + result3.length().toString());
    
    // Performance test calls
    int total = 0;
    for int i in 1..100 {
        total += complexExpressions1(i);
    }
    
    io:println("Total from complex expressions: " + total.toString());
    io:println("Performance test completed!");
}
EOF

echo "Generated $OUTPUT_FILE successfully!" >&2
echo "File contains $TARGET_FUNCTIONS functions plus imports, constants, and main function" >&2

# Count approximate tokens (rough estimate)
LINES=$(wc -l < "$OUTPUT_FILE")
ESTIMATED_TOKENS=$((LINES * 15))  # Rough estimate of ~15 tokens per line
echo "Estimated lines: $LINES" >&2
echo "Estimated tokens: ~$ESTIMATED_TOKENS" >&2